#!/bin/bash
#
# Pre-commit script that builds the PDF file
#
# To install:
#  ln -s hooks/pre-comit .git/hooks/pre-commit
#
# Resources:
#  - http://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error
#  - http://www.davidpashley.com/articles/writing-robust-shell-scripts/
#  - http://stackoverflow.com/questions/13998941/how-can-i-propagate-an-exit-status-from-expect-to-its-parent-bash-script
#  - http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-8.html
#  - http://codeinthehole.com/writing/tips-for-using-a-git-pre-commit-hook/

# Make sure working directory is clean
# and the index does not have the output PDF (chance for conflicts!)
git unstage cv_egon_geerardyn.pdf
git checkout HEAD cv_egon_geerardyn.pdf
git stash -q --keep-index

# Try to compile CV
echo $PWD
arara cv_egon_geerardyn.tex
ERRarara=$?  #store the exit code for readability

# Add freshly generated PDF to git
if [ "$ERRarara" -eq 0 ]; then
    git add -f cv_egon_geerardyn.pdf
fi

# Restore working directory
git stash pop -q
git checkout cv_egon_geerardyn.pdf

# And we're done
exit $ERRarara # pass on the error codes

